# :schema node_modules/wrangler/config-schema.json
name = "blog"
main = "src/worker.ts"
compatibility_date = "2025-04-09"
compatibility_flags = ["nodejs_compat"]

[[env.production.services]]
service = "contents"
binding = "CONTENTS"
[env.production.observability]
enabled = true

[[env.development.services]]
service = "contents-development"
binding = "CONTENTS"
