# :schema node_modules/wrangler/config-schema.json
name = "blog"
main = "src/worker.ts"
compatibility_date = "2025-04-09"
compatibility_flags = ["nodejs_compat"]

[[env.prd.services]]
service = "contents"
binding = "CONTENTS"
[env.prd.observability]
enabled = true

[[env.dev.services]]
service = "contents-dev"
binding = "CONTENTS"

[[env.local.services]]
service = "contents-local"
binding = "CONTENTS"
