# :schema node_modules/wrangler/config-schema.json
name = "contents"
main = "src/index.ts"
compatibility_date = "2025-04-09"

[env.prd.vars]
ENVIRONMENT = "prd"
[env.prd.observability]
enabled = true

[env.dev.vars]
ENVIRONMENT = "dev"

[env.local.vars]
ENVIRONMENT = "local"

[dev]
port = 8000
