# :schema node_modules/wrangler/config-schema.json
name = "contents"
main = "src/index.ts"
compatibility_date = "2025-04-09"
vars = { ENVIRONMENT = "dev" }

[observability]
enabled = true

[dev]
port = 8000

[env.production]
vars = { ENVIRONMENT = "production" }
