name: Package Size

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  bundle-analyze:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup GitHub App
        id: bot
        uses: re-taro/actions/gen-installation-token@v3.7.0
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
      - name: Setup | Node.js
        uses: re-taro/actions/setup-node@v3.7.0
        with:
          node-version-file: .tool-versions
      - name: Analyze | Bundle Size
        uses: preactjs/compressed-size-action@6fa0e7ca017120c754863b31123c5ee2860fd434 # 2.7.0
        with:
          pattern: app/dist/**/*.{js,json,html,xml,css}
          exclude: app/dist/~partytown/**/*.js
          repo-token: ${{ steps.bot.outputs.token }}
      - name: Revoke GitHub Apps token
        env:
          GITHUB_TOKEN: ${{ steps.bot.outputs.token }}
        run: |
          curl --location --silent --request DELETE \
            --url "${GITHUB_API_URL}/installation/token" \
            --header "Accept: application/vnd.github+json" \
            --header "X-GitHub-Api-Version: 2022-11-28" \
            --header "Authorization: Bearer ${GITHUB_TOKEN}"
