name: Main Workflow

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.0
      - name: Setup Node.js
        uses: re-taro/actions/setup-node@v3.3.1
        with:
          node-version-file: .tool-versions
      - name: Use turborepo cache
        uses: re-taro/actions/turbo-cache@v3.3.1
      - name: Build test
        run: pnpm build
        shell: sh
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.0
      - name: Setup Node.js
        uses: re-taro/actions/setup-node@v3.3.1
        with:
          node-version-file: .tool-versions
      - name: Use turborepo cache
        uses: re-taro/actions/turbo-cache@v3.3.1
      - name: Lint test
        run: pnpm lint
        shell: sh
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.0
      - name: Setup Node.js
        uses: re-taro/actions/setup-node@v3.3.1
        with:
          node-version-file: .tool-versions
      - name: Use turborepo cache
        uses: re-taro/actions/turbo-cache@v3.3.1
      - name: Unit test
        run: pnpm test
        shell: sh
