name: Main CI

on:
  pull_request:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup | Node.js
        uses: re-taro/actions/setup-node@v3.7.0
        with:
          node-version-file: .tool-versions
      - name: Run | Build
        run: pnpm run build
  lint-test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup | Node.js
        uses: re-taro/actions/setup-node@v3.7.0
        with:
          node-version-file: .tool-versions
      - name: Run | ESLint
        run: pnpm run lint:eslint
  type-test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup | Node.js
        uses: re-taro/actions/setup-node@v3.7.0
        with:
          node-version-file: .tool-versions
      - name: Setup | Build
        run: pnpm prebuild:content-collections
      - name: Run | tsc
        run: pnpm run lint:tsc
  prettier-test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup | Node.js
        uses: re-taro/actions/setup-node@v3.7.0
        with:
          node-version-file: .tool-versions
      - name: Run | Prettier
        run: pnpm run lint:prettier
  slug-test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup | Node.js
        uses: re-taro/actions/setup-node@v3.7.0
        with:
          node-version-file: .tool-versions
      - name: Run | Slug
        run: pnpm run lint:textlint
  unit-test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup | Node.js
        uses: re-taro/actions/setup-node@v3.7.0
        with:
          node-version-file: .tool-versions
      - name: Test | Unit
        run: pnpm run test:unit
  integration-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup | Node.js
        uses: re-taro/actions/setup-node@v3.7.0
        with:
          node-version-file: .tool-versions
      - name: Setup | Playwright
        uses: ./.github/actions/setup-playwright
      - name: Setup | Build
        run: pnpm build
      - name: Test | Integration
        run: |
          concurrently -k -s first -n "APP,TEST" -c "magenta,blue" \
            "pnpm start" \
            "wait-on http://127.0.0.1:8788 && pnpm test:integration"
