name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    outputs:
      release-created: ${{ steps.release.outputs['app--release-created'] }}
    steps:
      - uses: actions/checkout@v3.5.3
        with:
          fetch-depth: 0
      - id: release
        uses: google-github-actions/release-please-action@v3.7.11
        with:
          command: manifest
          config-file: .github/release-please-config.json
          manifest-file: .github/release-please-manifest.json
          release-type: node
          token: ${{ secrets.GITHUB_TOKEN }}
  deploy:
    needs: release
    if: ${{ needs.release.outputs.release-created }}
    runs-on: ubuntu-latest
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    steps:
      - uses: actions/checkout@v3.5.3
      - name: Setup Node.js
        uses: re-taro/actions/setup-node@v1.1.2
        with:
          node-version-file: .tool-versions
      - name: start deployment
        uses: bobheadxi/deployments@v1.4.0
        id: deployment
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: Production
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        id: deploy
        run: echo "url=$(vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }})" >> $GITHUB_OUTPUT
      - name: Update deployment status
        uses: bobheadxi/deployments@v1.4.0
        if: always()
        with:
          step: finish
          token: ${{ github.token }}
          status: ${{ job.status }}
          env: ${{ steps.deployment.outputs.env }}
          env_url: ${{ steps.deploy.outputs.url }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
