name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    outputs:
      has_changesets: ${{ steps.changesets.outputs.hasChangesets }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup Node.js
        uses: re-taro/actions/setup-node@v3.7.0
        with:
          node-version-file: .tool-versions
      - name: Setup GitHub App
        id: bot
        uses: re-taro/actions/gen-installation-token@v3.7.0
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
      - name: Create Release Pull Request
        id: changesets
        uses: changesets/action@06245a4e0a36c064a573d4150030f5ec548e4fcc # v1.4.10
        with:
          publish: pnpm changeset publish
        env:
          GITHUB_TOKEN: ${{ steps.bot.outputs.token }}
      - name: Revoke GitHub Apps token
        env:
          GITHUB_TOKEN: ${{ steps.bot.outputs.token }}
        run: |
          curl --location --silent --request DELETE \
            --url "${GITHUB_API_URL}/installation/token" \
            --header "Accept: application/vnd.github+json" \
            --header "X-GitHub-Api-Version: 2022-11-28" \
            --header "Authorization: Bearer ${GITHUB_TOKEN}"
  deploy:
    name: Deploy
    needs: release
    runs-on: ubuntu-latest
    if: ${{ needs.release.outputs.has_changesets == 'false' }}
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup Node.js
        uses: re-taro/actions/setup-node@v3.7.0
        with:
          node-version-file: .tool-versions
      - name: Deploy | Build
        run: pnpm build
      - name: Deploy | Deploy contents to Cloudflare Workers
        uses: cloudflare/wrangler-action@7a5f8bbdfeedcde38e6777a50fe685f89259d4ca # v3.13.1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: deploy --minify
          workingDirectory: apps/contents
      - name: Deploy | Deploy blog to Cloudflare Workers
        id: page
        uses: cloudflare/wrangler-action@7a5f8bbdfeedcde38e6777a50fe685f89259d4ca # v3.13.1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: deploy
          workingDirectory: apps/blog
